services:
  postgres:
    image: postgres:17
    command: -d 1
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "6543:5432" #  ← DB reachable on localhost:6543
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  neon-proxy:
    image: ghcr.io/timowilhelm/local-neon-http-proxy:main
    environment:
      - PG_CONNECTION_STRING=postgres://postgres:postgres@postgres:5432/main
    ports:
      - "3333:4444"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db_data: {}
